version: '3.4'
services:
  provider:
    image: oceanprotocol/provider-py:latest
    ports:
      - 8030:8030
    network_mode: host
    depends_on:
    - ocean-contracts
    environment:
      ARTIFACTS_PATH: "/ocean-contracts/artifacts"
      NETWORK_URL: ${NETWORK_RPC_URL}
      PARITY_URL: ${NETWORK_RPC_URL}
      PROVIDER_PRIVATE_KEY: ${PROVIDER_PRIVATE_KEY}
      LOG_LEVEL: ${PROVIDER_LOG_LEVEL}
      OCEAN_PROVIDER_URL: 'http://0.0.0.0:8030'
      OCEAN_PROVIDER_WORKERS: ${PROVIDER_WORKERS}
      IPFS_GATEWAY: ${PROVIDER_IPFS_GATEWAY}
      OCEAN_PROVIDER_TIMEOUT: '9000'
      OPERATOR_SERVICE_URL: ${OPERATOR_SERVICE_URL}
      AQUARIUS_URL: ${AQUARIUS_URL}
    volumes:
    - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
    - providerdb:/ocean-provider/db/
volumes:
  providerdb:
